// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: domains.sql

package database

import (
	"context"
	"time"
)

const createDomain = `-- name: CreateDomain :exec
INSERT INTO domains (id, owner_id, name, url, total_visits, total_unique, total_time, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateDomainParams struct {
	ID          string
	OwnerID     string
	Name        string
	Url         string
	TotalVisits int64
	TotalUnique int64
	TotalTime   int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) error {
	_, err := q.db.ExecContext(ctx, createDomain,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Url,
		arg.TotalVisits,
		arg.TotalUnique,
		arg.TotalTime,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getDomain = `-- name: GetDomain :one
SELECT id, owner_id, name, url, total_visits, total_unique, total_time, created_at, updated_at FROM domains WHERE id = ?
`

func (q *Queries) GetDomain(ctx context.Context, id string) (Domain, error) {
	row := q.db.QueryRowContext(ctx, getDomain, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Url,
		&i.TotalVisits,
		&i.TotalUnique,
		&i.TotalTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDomains = `-- name: GetDomains :many
SELECT id, owner_id, name, url, total_visits, total_unique, total_time, created_at, updated_at FROM domains
`

func (q *Queries) GetDomains(ctx context.Context) ([]Domain, error) {
	rows, err := q.db.QueryContext(ctx, getDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Domain
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Url,
			&i.TotalVisits,
			&i.TotalUnique,
			&i.TotalTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthStats = `-- name: GetMonthStats :one
SELECT
  COUNT(*) AS total_count,
  COUNT(CASE WHEN visitorStatus = 'new' THEN 1 END) AS new_visitor_count
FROM visits
WHERE domain = ?
  AND createdAt >= date('now', '-30 days')
`

type GetMonthStatsRow struct {
	TotalCount      int64
	NewVisitorCount int64
}

func (q *Queries) GetMonthStats(ctx context.Context, domain string) (GetMonthStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getMonthStats, domain)
	var i GetMonthStatsRow
	err := row.Scan(&i.TotalCount, &i.NewVisitorCount)
	return i, err
}

const getPrevMonthStats = `-- name: GetPrevMonthStats :one
SELECT
  COUNT(*) AS total_count,
  COUNT(CASE WHEN visitorStatus = 'new' THEN 1 END) AS new_visitor_count
FROM visits 
WHERE domain = ?
  AND createdAt >= date('now', '-60 days')
  AND createdAt < date('now', '-30 days')
`

type GetPrevMonthStatsRow struct {
	TotalCount      int64
	NewVisitorCount int64
}

func (q *Queries) GetPrevMonthStats(ctx context.Context, domain string) (GetPrevMonthStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getPrevMonthStats, domain)
	var i GetPrevMonthStatsRow
	err := row.Scan(&i.TotalCount, &i.NewVisitorCount)
	return i, err
}

const updateDomain = `-- name: UpdateDomain :exec
UPDATE domains SET 
  total_visits = total_visits + ?,
  total_unique = total_unique + ?
WHERE id = ?
`

type UpdateDomainParams struct {
	TotalVisits int64
	TotalUnique int64
	ID          string
}

func (q *Queries) UpdateDomain(ctx context.Context, arg UpdateDomainParams) error {
	_, err := q.db.ExecContext(ctx, updateDomain, arg.TotalVisits, arg.TotalUnique, arg.ID)
	return err
}
