// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: domains.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (id, owner_id,name,url,total_visits,total_unique,total_time,created_at,updated_at)
VALUES ($1, $2, $3, $4, $5, $6,$7,$8,$9)
RETURNING id, owner_id, name, url, total_visits, total_unique, total_time, created_at, updated_at
`

type CreateDomainParams struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	Name        string
	Url         string
	TotalVisits int32
	TotalUnique int32
	TotalTime   int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRowContext(ctx, createDomain,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Url,
		arg.TotalVisits,
		arg.TotalUnique,
		arg.TotalTime,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Url,
		&i.TotalVisits,
		&i.TotalUnique,
		&i.TotalTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDomain = `-- name: GetDomain :one

Select id, owner_id, name, url, total_visits, total_unique, total_time, created_at, updated_at FROM domains WHERE id = $1
`

func (q *Queries) GetDomain(ctx context.Context, id uuid.UUID) (Domain, error) {
	row := q.db.QueryRowContext(ctx, getDomain, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Url,
		&i.TotalVisits,
		&i.TotalUnique,
		&i.TotalTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDomains = `-- name: GetDomains :many
SELECT id, owner_id, name, url, total_visits, total_unique, total_time, created_at, updated_at FROM domains
`

func (q *Queries) GetDomains(ctx context.Context) ([]Domain, error) {
	rows, err := q.db.QueryContext(ctx, getDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Domain
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Url,
			&i.TotalVisits,
			&i.TotalUnique,
			&i.TotalTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
