// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: domain_follows.sql

package database

import (
	"context"
	"time"
)

const createDomainFollow = `-- name: CreateDomainFollow :exec
INSERT INTO domain_follows (id, created_at, user_id, domain_id, domain_name)
VALUES (?, ?, ?, ?, ?)
`

type CreateDomainFollowParams struct {
	ID         string
	CreatedAt  time.Time
	UserID     string
	DomainID   string
	DomainName string
}

func (q *Queries) CreateDomainFollow(ctx context.Context, arg CreateDomainFollowParams) error {
	_, err := q.db.ExecContext(ctx, createDomainFollow,
		arg.ID,
		arg.CreatedAt,
		arg.UserID,
		arg.DomainID,
		arg.DomainName,
	)
	return err
}

const getDomainsForUser = `-- name: GetDomainsForUser :many
SELECT id, created_at, user_id, domain_id, domain_name FROM domain_follows WHERE user_id = ?
`

func (q *Queries) GetDomainsForUser(ctx context.Context, userID string) ([]DomainFollow, error) {
	rows, err := q.db.QueryContext(ctx, getDomainsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DomainFollow
	for rows.Next() {
		var i DomainFollow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.DomainID,
			&i.DomainName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
