// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Domain struct {
	ID          string
	OwnerID     string
	Name        string
	Url         string
	TotalVisits int64
	TotalUnique int64
	TotalTime   int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type DomainFollow struct {
	ID         string
	CreatedAt  time.Time
	UserID     string
	DomainID   string
	DomainName string
}

type Pagevisit struct {
	Createdat time.Time
	Domain    string
	Page      string
}

type PasswordReset struct {
	ID         string
	Expiration time.Time
	Email      string
	Valid      bool
	Token      string
}

type User struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Email     string
	Passhash  string
	ApiKey    string
}

type Visit struct {
	Createdat     time.Time
	Visitorstatus string
	Visitduration int64
	Domain        string
	Visitfrom     string
	Browser       string
	Device        string
	Os            string
	Bounce        bool
}
