// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package database

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

type Visit struct {
	ID            string
	Createdat     time.Time
	Country       string
	Ip            string
	Visitorstatus string
	Domain        string
	Visitfrom     string
}
