// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"time"
)

const createPasswordReset = `-- name: CreatePasswordReset :exec
INSERT INTO password_resets (id, expiration, email, valid, token)
VALUES (?, ?, ?, ?, ?)
`

type CreatePasswordResetParams struct {
	ID         string
	Expiration time.Time
	Email      string
	Valid      bool
	Token      string
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) error {
	_, err := q.db.ExecContext(ctx, createPasswordReset,
		arg.ID,
		arg.Expiration,
		arg.Email,
		arg.Valid,
		arg.Token,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, created_at, updated_at, name, api_key, email, passhash)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	ApiKey    string
	Email     string
	Passhash  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.ApiKey,
		arg.Email,
		arg.Passhash,
	)
	return err
}

const getUserByAPIKey = `-- name: GetUserByAPIKey :one
SELECT id, created_at, updated_at, name, email, passhash, api_key FROM users WHERE api_key = ?
`

func (q *Queries) GetUserByAPIKey(ctx context.Context, apiKey string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByAPIKey, apiKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.Passhash,
		&i.ApiKey,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, name, email, passhash, api_key FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.Passhash,
		&i.ApiKey,
	)
	return i, err
}

const resetInvalid = `-- name: ResetInvalid :exec
UPDATE password_resets SET valid = 0 WHERE id = ?
`

func (q *Queries) ResetInvalid(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, resetInvalid, id)
	return err
}

const resetPassword = `-- name: ResetPassword :one
SELECT id, expiration, email, valid, token FROM password_resets WHERE token = ?
`

func (q *Queries) ResetPassword(ctx context.Context, token string) (PasswordReset, error) {
	row := q.db.QueryRowContext(ctx, resetPassword, token)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.Expiration,
		&i.Email,
		&i.Valid,
		&i.Token,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users SET passhash = ? WHERE id = ?
`

type UpdatePasswordParams struct {
	Passhash string
	ID       string
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.Passhash, arg.ID)
	return err
}
