// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: visits.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createVisit = `-- name: CreateVisit :one
INSERT INTO visits(createdat,visitorstatus,visitDuration,domain,visitfrom)
VALUES($1,$2,$3,$4,$5)
RETURNING createdat, visitorstatus, visitduration, domain, visitfrom
`

type CreateVisitParams struct {
	Createdat     time.Time
	Visitorstatus string
	Visitduration int32
	Domain        uuid.UUID
	Visitfrom     string
}

func (q *Queries) CreateVisit(ctx context.Context, arg CreateVisitParams) (Visit, error) {
	row := q.db.QueryRowContext(ctx, createVisit,
		arg.Createdat,
		arg.Visitorstatus,
		arg.Visitduration,
		arg.Domain,
		arg.Visitfrom,
	)
	var i Visit
	err := row.Scan(
		&i.Createdat,
		&i.Visitorstatus,
		&i.Visitduration,
		&i.Domain,
		&i.Visitfrom,
	)
	return i, err
}
